export const Genre = [
    // ===== GREAT =====
    "unknown inventors",
    "codebreakers",
    "spies",
    "criminal masterminds",
    "revolutionaries",
    "whistleblowers",
    "military strategists",
    "assassins",
    "hackers",
    "smugglers",
    "arms dealers",
    "resistance fighters",
    "corporate insiders",
    "political operators",
    "shadow financiers",
    "black market surgeons",
    "cryptographers",
    "signal interceptors",
    "interrogators",
    "human traffickers",
    "data brokers",
    "biohackers",
    "identity thieves",
    "document launderers",
    "undercover journalists",
    "war correspondents",
    "black ops logisticians",
    "psychological warfare designers",
    "forensic accountants",
    "election strategists",
    "diplomatic backchannel negotiators",
    "electronic warfare specialists",

    // ===== GOOD =====
    "engineers",
    "nurses",
    "scientists",
    "diplomats",
    "activists",
    "journalists",
    "pilots",
    "detectives",
    "medical researchers",
    "explorers",
    "propaganda writers",
    "economic reformers",
    "religious leaders",
    "prison informants",
    "war photographers",
    "deep-sea divers",
    "satellite operators",
    "drone pilots",
    "cyber security analysts",
    "gene editors",
    "space engineers",
    "rocket technicians",
    "disaster responders",
    "fire investigators",
    "linguists",
    "negotiators",
    "hostage mediators",
    "mercenaries",
    "bodyguards",
    "survival experts",
    "weapons testers",
    "demolition experts",
    "railway controllers",
    "air traffic controllers",
    "submarine crews",
    "treasure hunters",
    "storm chasers",
    "park rangers",
    "genetic archivists",
    "memory researchers",
    "AI trainers",
    "algorithm designers",
    "social engineers (psychological)",
    "speechwriters (hidden influence)",
    "ghostwriters",
    "trend manipulators",
    "influencer handlers",
    "dark web moderators",
    "behavioral profilers",
    "microbiologists",
    "epidemiologists",
    "toxicologists",
    "antidote developers",
    "climate engineers",
    "seismologists",
    "volcanologists",
    "asteroid trackers",
    "orbital mechanics experts",
    "surveillance operators",
    "CCTV analysts",
    "DNA forensic analysts",
    "cold case investigators",
    "missing persons trackers",
    "disaster forecasters",
    "evacuation planners",
    "bunker designers",
    "tunnel engineers",
    "rare artifact hunters",
    "lost language decoders",
    "ancient script translators",
    "truth verification analysts",
    "fact-checking operatives",
    "neural interface developers",
    "brain-computer engineers",
    "VR world builders",
    "metaverse architects",
    "gamification engineers",
    "addiction researchers",
    "attention engineers",
    "persuasion experts",
    "decision architects",
    "behavioral economists",
    "risk modelers",
    "future forecasters",
    "trend predictors",
    "scenario planners",
    "systems thinkers",

    // ===== NORMAL =====
    "factory workers",
    "industrial designers",
    "ship captains",
    "artists",
    "architects",
    "bankers",
    "miners",
    "teachers",
    "urban planners",
    "insurance fraud experts",
    "auctioneers",
    "art thieves",
    "museum curators",
    "antique smugglers",
    "border agents",
    "cartographers",
    "zookeepers (illegal trade links)",
    "supply chain masterminds",
    "ice road truckers",
    "wildlife traffickers",
    "timekeepers",
    "clockmakers",
    "locksmiths",
    "safecrackers",
    "body double actors",
    "impersonators",
    "lie detectors",
    "polygraph examiners",
    "food tasters (royal/elite)",
    "poison specialists",
    "weather manipulators (experimental)",
    "space debris analysts",
    "signal jammers",
    "facial recognition trainers",
    "biometric hackers",
    "underground city designers",
    "black market auction runners",
    "conspiracy researchers",
    "information suppressors",
    "data erasers",
    "digital cleaners (reputation control)",
    "online identity creators",
    "fake persona builders",
    "sleep scientists",
    "dream analysts",
    "navigation system designers (GPS etc.)",
    "energy grid operators",
    "power plant controllers",
    "water system engineers",
    "waste management strategists",
    "food supply chain analysts",
    "accident reconstruction experts",
    "sanctions evasion experts",
    "financial crisis managers",
    "currency manipulators",
    "campaign spin doctors",
    "peace treaty architects",
    "refugee camp coordinators",
    "humanitarian logisticians",
    "pandemic response planners",
    "biolab safety officers",
    "ethnographers",
    "cultural preservationists",
    "oral historians",
    "symbol analysts",
    "semiotics experts",
    "narrative psychologists",
    "cult deprogrammers",
    "radicalization researchers",
    "deradicalization operatives",
    "security clearance investigators",
    "background check analysts",
    "insider threat analysts",
    "treasury custodians",
    "vault designers",
    "currency printers",
    "mint officials",
    "time synchronization engineers",
    "materials scientists",
    "nanotechnologists",
    "fusion scientists",
    "quantum engineers",

    // ===== EXPERIMENTAL =====
    "myth creators",
    "ritual specialists",
    "exorcists",
    "fortune tellers",
    "crisis actors (propaganda use)",
    "voice actors (covert propaganda)",
    "voice forgery experts",
    "mind control researchers",
    "memory manipulators (experimental)",
    "sensory illusion designers",
    "chaos theorists"
]